// Package moodle knows the demo site's code tree: layout detection across
// the Moodle 5.1 public/ split, config.php generation, and running Moodle
// CLI scripts.
//
// Layout facts (verified against MOODLE_501/502_STABLE and mpd's tooling):
// config-dist.php, lib/setup.php and admin/cli/* live at the repo ROOT in
// every supported version; 5.1+ adds public/ as the web docroot and moves
// some admin tools under it. So config.php always goes at the root, the
// docroot varies, and each CLI script path is resolved individually.
package moodle

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mutms/mdl-demo/go/internal/execx"
)

const (
	// Root is where mudev assembles the code tree.
	Root = "/srv/projects/demo"
	// Dataroot lives outside the webroot and is owned by www-data.
	Dataroot = "/srv/data/demo"
)

// Detected reports whether a Moodle tree is present.
func Detected() bool {
	return exists(filepath.Join(Root, "version.php")) ||
		exists(filepath.Join(Root, "public", "version.php"))
}

// Docroot is what Apache serves: public/ when the tree has the 5.1+ split.
func Docroot() string {
	if exists(filepath.Join(Root, "public", "version.php")) {
		return filepath.Join(Root, "public")
	}
	return Root
}

// HasRouter reports whether the docroot ships r.php (Moodle 5.0+); the
// Apache rewrite to /r.php must not be emitted without it or unknown URLs
// loop instead of 404ing.
func HasRouter() bool {
	return exists(filepath.Join(Docroot(), "r.php"))
}

// resolveDir returns the directory to run a CLI script from: the root, or
// public/ for the tools that moved there in 5.1.
func resolveDir(rel string) (string, error) {
	if exists(filepath.Join(Root, rel)) {
		return Root, nil
	}
	if exists(filepath.Join(Root, "public", rel)) {
		return filepath.Join(Root, "public"), nil
	}
	return "", fmt.Errorf("%s not found under %s or %s/public", rel, Root, Root)
}

// RunCLI runs a Moodle CLI script as www-data — the same user php-fpm runs
// as, so everything either writes into the dataroot is usable by the other.
func RunCLI(logf execx.Logf, rel string, args ...string) error {
	return runCLI(logf, nil, rel, args...)
}

// runCLI is RunCLI with secret values masked in the echoed command line, for a
// script invoked with a password on its argv.
func runCLI(logf execx.Logf, secrets []string, rel string, args ...string) error {
	dir, err := resolveDir(rel)
	if err != nil {
		return err
	}
	cmd := append([]string{"-u", "www-data", "--", "php", rel}, args...)
	return execx.RunSecret(logf, secrets, dir, "runuser", cmd...)
}

// InstallDatabase runs Moodle's CLI installer against the already-written
// config.php. Flags proven by mpd's install tooling. The admin email is
// deliberately hardcoded — a demo site never sends mail (noemailever).
func InstallDatabase(logf execx.Logf, fullname, shortname, adminpass string) error {
	return runCLI(logf, []string{adminpass}, "admin/cli/install_database.php",
		"--agree-license",
		"--fullname="+fullname,
		"--shortname="+shortname,
		"--summary=mdl-demo site",
		"--adminpass="+adminpass,
		"--adminemail=admin@example.com",
	)
}

// Cron runs Moodle cron (used by moodle-cron.service via `mdl-demo cron`).
func Cron(logf execx.Logf) error {
	return RunCLI(logf, "admin/cli/cron.php")
}

// sslproxy returns the config line for an https wwwroot: TLS always ends
// outside this container (a reverse proxy or a tunnel speaks https to the
// browser and plain http to Apache), which is exactly what $CFG->sslproxy
// tells Moodle. Without it, Moodle sees an http request for an https wwwroot
// and redirects in a loop.
func sslproxy(wwwroot string) string {
	if strings.HasPrefix(wwwroot, "https://") {
		return "$CFG->sslproxy = true; // TLS is terminated in front of the container\n"
	}
	return ""
}

// WriteConfig generates config.php at the tree root. Regenerated on every
// install; the demo site is machine-owned so there is no user-editable half
// (unlike mpd's config.php / config-mpd.php split).
func WriteConfig(wwwroot string) error {
	config := `<?php
// config.php — generated by mdl-demo, regenerated on install/reset.
// Custom settings will be lost; this is a disposable demo site.

unset($CFG);
global $CFG;
$CFG = new stdClass();

$CFG->dbtype    = 'pgsql';
$CFG->dblibrary = 'native';
$CFG->dbhost    = 'localhost';
$CFG->dbname    = 'demo';
$CFG->dbuser    = 'demo';
$CFG->dbpass    = 'demo';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = array(
    'dbpersist' => 0,
);

$CFG->wwwroot  = '` + wwwroot + `';
` + sslproxy(wwwroot) + `
$CFG->dataroot = '` + Dataroot + `';
$CFG->directorypermissions = 02777;

// Router (Moodle 5.0+): Apache rewrites unknown URLs to /r.php, so clean
// URLs work; telling Moodle silences the environment check.
$CFG->routerconfigured = true;

$CFG->admin = 'admin';

// The code tree is root-owned and the web server only reads it, so web-based
// plugin installation cannot work; this makes Moodle hide those affordances
// instead of failing on them. Plugins come in via recipes/mudev only.
$CFG->disableupdateautodeploy = true;

// Demo failsafes: never send real mail, and tell Moodle the site is not
// reachable from the internet — blocks site registration and other
// public outreach (localhost-only demo).
$CFG->noemailever = true;
$CFG->noreplyaddress = 'noreply@example.com';
$CFG->site_is_public = false;

$CFG->cronclionly = 0;
$CFG->cron_keepalive = '0';

require_once(__DIR__ . '/lib/setup.php'); // Do not edit
`
	return os.WriteFile(filepath.Join(Root, "config.php"), []byte(config), 0644)
}

// WriteSSOScript drops mdldemo-login.php into the docroot: the public
// endpoint that turns a single-use token (minted by internal/sso into
// <dataroot>/mdldemo-sso/) into a logged-in Moodle session. Consume-then-login
// so a scanned-twice QR has exactly one winner.
func WriteSSOScript() error {
	config := "config.php"
	if Docroot() != Root {
		config = "../config.php"
	}
	script := `<?php
// mdldemo-login.php — generated by mdl-demo: single-use login links for the
// management console's "Log in…" buttons and QR codes. Tokens are minted by
// the console into <dataroot>/mdldemo-sso/ and consumed here on first use.

require(__DIR__ . '/` + config + `');

$token = optional_param('token', '', PARAM_ALPHANUMEXT);
$dir = $CFG->dataroot . '/mdldemo-sso';
$fail = function() {
    http_response_code(403);
    header('Content-Type: text/plain; charset=utf-8');
    die('This login link is invalid, expired, or was already used.');
};
if ($token === '' || !is_dir($dir)) {
    $fail();
}
$file = $dir . '/' . hash('sha256', $token) . '.json';
$data = @file_get_contents($file);
@unlink($file); // single use: consume before logging in, one winner per token
if ($data === false) {
    $fail();
}
$info = json_decode($data);
if (!$info || empty($info->username) || empty($info->expires) || $info->expires < time()) {
    $fail();
}
$user = get_complete_user_data('username', $info->username, null, false);
if (!$user || !empty($user->deleted) || !empty($user->suspended)) {
    $fail();
}
complete_user_login($user);
redirect($CFG->wwwroot . '/');
`
	return os.WriteFile(filepath.Join(Docroot(), "mdldemo-login.php"), []byte(script), 0644)
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
