// Package apache swaps the port-8080 vhost between the shipped placeholder
// page and the generated Moodle site.
package apache

import (
	"os"

	"github.com/mutms/mdl-demo/internal/execx"
	"github.com/mutms/mdl-demo/internal/svc"
)

const sitePath = "/etc/apache2/sites-available/demo.conf"

// WriteVhost renders the Moodle vhost. The router rewrite is only emitted
// when the tree ships r.php (Moodle 5.0+); on older trees rewriting a
// missing target would loop instead of returning 404.
func WriteVhost(docroot string, router bool) error {
	conf := `# demo.conf — generated by mdl-demo, regenerated on install.
<VirtualHost *:8080>
    DocumentRoot ` + docroot + `
    <Directory ` + docroot + `>
        Require all granted
        AllowOverride None
        Options -Indexes
`
	// The router rewrite sits INSIDE <Directory>: in VirtualHost context
	// %{REQUEST_FILENAME} is not filesystem-resolved yet (it equals the
	// URI), so !-f would match every request and even real files would get
	// routed to /r.php. Per-directory rewrites see the mapped path.
	if router {
		conf += `        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^ /r.php [QSA,L]
`
	}
	conf += `    </Directory>
    <FilesMatch \.php$>
        SetHandler "proxy:unix:/run/php/php8.3-fpm.sock|fcgi://localhost"
    </FilesMatch>
    <Files "config.php">
        Require all denied
    </Files>
    RedirectMatch 404 "/\."
    RedirectMatch 404 "^/(vendor|node_modules)/"
</VirtualHost>
`
	return os.WriteFile(sitePath, []byte(conf), 0644)
}

// EnableDemo switches 8080 from the placeholder to the Moodle vhost.
func EnableDemo(logf execx.Logf) error {
	if err := execx.Run(logf, "", "a2dissite", "-q", "000-placeholder"); err != nil {
		return err
	}
	if err := execx.Run(logf, "", "a2ensite", "-q", "demo"); err != nil {
		return err
	}
	return svc.Current().ReloadApache(logf)
}

// RestorePlaceholder switches 8080 back and removes the generated vhost.
func RestorePlaceholder(logf execx.Logf) error {
	if err := execx.Run(logf, "", "a2dissite", "-q", "demo"); err != nil {
		return err
	}
	if err := execx.Run(logf, "", "a2ensite", "-q", "000-placeholder"); err != nil {
		return err
	}
	if err := os.Remove(sitePath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return svc.Current().ReloadApache(logf)
}
