// Package apache swaps the site vhost (container port 8082) between the
// shipped placeholder page and the generated Moodle site.
package apache

import (
	"os"
	"strconv"

	"github.com/mutms/mdl-demo/go/internal/execx"
	"github.com/mutms/mdl-demo/go/internal/svc"
)

const sitePath = "/etc/apache2/sites-available/demo.conf"

// Port is the container-internal site port; Apache's Listen and the
// placeholder vhost in the image use the same number (state.SiteListen).
const Port = 8082

// WriteVhost renders the Moodle vhost. The router rewrite is only emitted
// when the tree ships r.php (Moodle 5.0+); on older trees rewriting a
// missing target would loop instead of returning 404.
//
// wwwroot becomes a canonical ServerName (scheme included): Apache builds
// self-referential redirects — mod_dir's trailing-slash one above all — from
// the connection it sees, plain http on 8082, which behind TLS termination
// yields http://host:8082/... . UseCanonicalName On + a scheme-qualified
// ServerName makes those redirects use the wwwroot instead. The vhost must
// therefore be regenerated whenever the wwwroot changes (install, tunnel).
func WriteVhost(wwwroot, docroot string, router bool) error {
	conf := `# demo.conf — generated by mdl-demo, regenerated on install and
# whenever the site URL changes (tunnel start/stop).
<VirtualHost *:` + strconv.Itoa(Port) + `>
    ServerName ` + wwwroot + `
    UseCanonicalName On
    DocumentRoot ` + docroot + `
    <Directory ` + docroot + `>
        Require all granted
        AllowOverride None
        Options -Indexes
`
	// The router rewrite sits INSIDE <Directory>: in VirtualHost context
	// %{REQUEST_FILENAME} is not filesystem-resolved yet (it equals the
	// URI), so !-f would match every request and even real files would get
	// routed to /r.php. Per-directory rewrites see the mapped path.
	if router {
		conf += `        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^ /r.php [QSA,L]
`
	}
	conf += `    </Directory>
    <FilesMatch \.php$>
        SetHandler "proxy:unix:/run/php/php8.3-fpm.sock|fcgi://localhost"
    </FilesMatch>
    <Files "config.php">
        Require all denied
    </Files>
    RedirectMatch 404 "/\."
    RedirectMatch 404 "^/(vendor|node_modules)/"
</VirtualHost>
`
	return os.WriteFile(sitePath, []byte(conf), 0644)
}

// EnableDemo switches the site port from the placeholder to the Moodle vhost.
func EnableDemo(logf execx.Logf) error {
	if err := disableSite(logf, "000-placeholder"); err != nil {
		return err
	}
	if err := enableSite(logf, "demo"); err != nil {
		return err
	}
	return svc.Current().ReloadApache(logf)
}

// DisableDemo switches the site port to the placeholder WITHOUT touching the
// generated vhost — for taking the site offline briefly (a backup) and
// bringing it back with EnableDemo.
func DisableDemo(logf execx.Logf) error {
	if err := disableSite(logf, "demo"); err != nil {
		return err
	}
	if err := enableSite(logf, "000-placeholder"); err != nil {
		return err
	}
	return svc.Current().ReloadApache(logf)
}

// RestorePlaceholder switches the placeholder back and removes the generated vhost.
func RestorePlaceholder(logf execx.Logf) error {
	if err := disableSite(logf, "demo"); err != nil {
		return err
	}
	if err := enableSite(logf, "000-placeholder"); err != nil {
		return err
	}
	if err := os.Remove(sitePath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return svc.Current().ReloadApache(logf)
}

// enableSite enables an apache site unless it already is, and disableSite
// disables one only if it is currently enabled. The guard keeps site switching
// idempotent: a2ensite/a2dissite exit non-zero (and, for a never-enabled site,
// print "Site … does not exist!") when asked to move a site that is already in
// the target state, which would otherwise abort a re-run of reset or install
// partway — the exact failure seen after an interrupted reset.
func enableSite(logf execx.Logf, name string) error {
	if siteEnabled(name) {
		return nil
	}
	return execx.Run(logf, "", "a2ensite", "-q", name)
}

func disableSite(logf execx.Logf, name string) error {
	if !siteEnabled(name) {
		return nil
	}
	return execx.Run(logf, "", "a2dissite", "-q", name)
}

// siteEnabled reports whether apache currently has the named site enabled.
// `a2query -s <name>` exits 0 only for an enabled site (disabled or absent
// exits non-zero), which is exactly the state these guards need.
func siteEnabled(name string) bool {
	_, err := execx.Output("", "a2query", "-s", name)
	return err == nil
}
